name: smart_arrays_compress
version: "3.0.0"
description: Compresses large one- or two-dimensional arrays (vectors, matrices) to a reduced format retaining minimum and maximum values. Can also expand an array by interpolation.
homepage: https://github.com/timmaffett/smart_packages
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  pedantic: ^1.7.0
  smart_arrays_base: ^2.0.9

