name: smart_lorentz_gauss
version: "3.0.0"
description: Provides functionalities to compute mixed Lorentz-Gauss line shapes, also called n-dimensional Pseudo-Voigt function.
homepage: https://github.com/timmaffett/smart_packages
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_plot_polyline: ^2.0.8
