name: smart_arrays_peaks
version: "2.1.3"
author: Dr. Bruno Guigas <specpad@gmail.com>
description: Provides functions to detect (search, pick) peaks (maximum values) in one- or two-dimensional arrays, also suitable for noisy data.
homepage: https://smart.specpad.bplaced.net
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_base: ^2.0.0
  smart_arrays_sample_data: ^2.0.3
  smart_arrays_plot_polyline: ^2.1.0
  smart_lorentz_gauss: ^2.1.2

