name: smart_arrays_peaks
version: "3.0.0"
description: Provides functions to detect (search, pick) peaks (maximum values) in one- or two-dimensional arrays, also suitable for noisy data.
homepage: https://github.com/timmaffett/smart_packages
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  smart_arrays_base: #^3.0.0
    path: ../smart_arrays_base

dev-dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^2.0.1
  