name: smart_arrays_contour_finder
version: "2.0.6"
author: Dr. Bruno Guigas <specpad@gmail.com>
description: This package contours the 3-dimensional surface represented by the values f(x,y) of a matrix. The detected contour lines are passed on to a user-provided renderer.
homepage: https://smart.specpad.bplaced.net
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_base: ^2.0.9
  smart_lorentz_gauss: ^2.1.2
  smart_arrays_plot_polyline: ^2.1.7






