name: smart_arrays_sample_data
version: "2.0.5"
author: Dr. Bruno Guigas <specpad@gmail.com>
description: Creates 1D and 2D arrays representing functions such as sine, cosine and others to be used as easily accessible sample data for many purposes.
homepage: https://smart.specpad.bplaced.net
environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_plot_polyline: ^2.0.11
  smart_lorentz_gauss: ^2.1.0
  smart_arrays_numerics: ^2.1.1
