name: smart_arrays_base
version: "3.0.0"
description: Provides basic functionalities for 1- and 2-dimensional arrays. Minima/maxima. Split, shuffle, swap, extract, extend. Submatrices, rows, columns, projections, sums.
homepage: https://github.com/timmaffett/smart_packages
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  pedantic: ^1.7.0

