name: smart_arrays_lmfit
version: "3.0.0"
description: Fits (x, y) data given as arrays to a specified model function using the  Levenberg-Marquardt algorithm.
homepage: https://github.com/timmaffett/smart_packages
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_numerics: ^2.0.0
  smart_arrays_plot_polyline: ^2.1.0
