name: smart_arrays_lmfit
version: "2.0.8"
author: Dr. Bruno Guigas <specpad@gmail.com>
description: Fits (x, y) data given as arrays to a specified model function using the  Levenberg-Marquardt algorithm.
homepage: https://smart.specpad.bplaced.net
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
  smart_arrays_numerics: ^2.0.0
  smart_arrays_plot_polyline: ^2.1.0
