name: smart_arrays_dbstore
version: "3.0.0"
description: Storing 1D or 2D arrays with their metadata inside indexedDB databases on the local device (for WEB applications).
homepage: https://github.com/timmaffett/smart_packages
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^2.0.1
  smart_arrays_base: #^3.0.0
    path: ../smart_arrays_base
